name: Software deploy workflow

on:
  workflow_dispatch:
    inputs:
      node-version:
        description: 'Some numeric value'
        required: false
        default: '0'

env:
  BUILD_PREFIX: build-
  RC_PREFIX: rc-
  RELEASE_PREFIX: release-
  
  
jobs:
  consecutiveness:
    runs-on: ubuntu-latest
    steps:
    - uses: mktcode/consecutive-workflow-action@e2e008186aa210faacd68ec30f6ac236f7e2f435
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  labelWhenApproved:
    runs-on: ubuntu-latest
    needs: [ consecutiveness ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Show inputs
        run: |
          echo Using version ${{ github.events.inputs.node-version }}
          echo or is it using version ${github.events.inputs.node-version}
          echo BUILD_PREFIX: ${BUILD_PREFIX}
          echo RC_PREFIX: ${RC_REFIX}
          echo RELEASE_PREFIX: ${RELEASE_PREFIX}
        shell: bash
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ github.events.inputs.node-version }}
          cache: 'npm'
          registry-url: 'https://npm.pkcg.github.com'
      - name: Run deploy stuff
        run: |
          for item in [0..6]
          do
            echo running loop item ${item}
            sleep 10
          done
        shell: bash
