name: test-consecutiveness

on:
  workflow_dispatch:
    inputs:
      node-version:
        description: Input node version number
        required: false
        default: '10.24.1'

env:
  BUILD_PREFIX: build-

jobs:
  check-consecutiveness:
    runs-on: ubuntu-latest
    steps:
      - name: Check Consecutiveness
        uses: mktcode/consecutive-workflow-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    needs: [ check-consecutiveness ]
    steps:
    - name: Show selected version
      run: |
        echo Using build prefix: ${BUILD_PREFIX}
        echo Installing node version: ${{ github.events.inputs.node-version }}
      shell: bash
    - name: install node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ github.events.inputs.node-version }}
        cache: 'npm'
        registry-url: 'https://npm.pkg.github.com'
    - name: Keep it busy
      run: |
        for item in {0..6}
        do
          echo Running $item
          sleep 10
        done
      shell: bash
      
